blank_issues_enabled: false
contact_links:
  - name: Get help or ask questions from the Miyoo Mini community on Discord (1,500+ members, very active)
    url: https://discord.com/channels/529983248114122762/891336865540620338/
    about: Join the Discord for community-powered support!
  - name: Get help or ask questions from the Miyoo Mini community on Reddit (4,000+ members, very active)
    url: https://www.reddit.com/r/MiyooMini/
    about: Join the SubReddit for community-powered support!
