blank_issues_enabled: false
contact_links:
  - name: Get help from the Miyoo Mini community on Discord
    url: https://discord.com/channels/529983248114122762/891336865540620338/
    about: Join the Discord for community-powered support!
